### ISSUE TITLE
KC3改数据提交

### ISSUE THREAD

**Issue by Javran** [Gizeta/poi-statistics#10]
想给 [KC3改](https://github.com/KC3Kai/KC3Kai) 做一个向poi-statistics发送数据的功能,目前已经有kancolle-db的集成了,应该实现起来难度不大,想询问一下接受什么样的数据(建造/掉落/开发 etc.)以及对应的接口,是否有相关文档之类的?

**Comment by Gizeta** [comment]
poi-statistics本身并没有收集数据的服务器，所有的数据来自[poi-server](https://github.com/poooi/poi-server)，如果对数据收集方面有任何建议或意见，可以到[poi-server](https://github.com/poooi/poi-server/issues)提交issue。

目前已有建造、开发、掉落及活动图甲乙丙选择的收集接口，但以后不限于这些。

文档方面暂时还没有，可以参考其他插件的实现（[poi](https://github.com/poooi/plugin-report)、[74eo](https://github.com/tsanie/ElectronicObserver/tree/makai/Plugins/DBSender)、[KCV](https://github.com/huoyaoyuan/KCVPlugins)）及[poi-server](https://github.com/poooi/poi-server)源代码。

**Comment by Javran** [comment]
感谢! 原来找错地方了(
研究一下,有问题去那边问了.
