### ISSUE TITLE
关于掉落率统计的建议

### ISSUE THREAD

**Issue by mazhen8u8** [Gizeta/poi-statistics#2]
非常高兴可以看到一个新的掉落统计站点，目前类似的统计站点除了poi以外，还有背锅GO和KANCOLLE-DB，这三个站点各有优势。
目前关于掉落率统计，有个很烦人的问题，就是活动分甲乙丙三个难度，然后掉落时战斗分SAB三种结果。这事实上需要把一个点的掉落情况分成9种条件考虑。然而不论是db站还是poi，都没有彻底分成9种情况。DB只分了3种，完全不分甲乙丙，而POI则分别分了甲乙丙和SAB，却没有做交叉条件的统计。

这导致数据的不准确，很显然的就是甲乙丙分布中，甲掉落率一般比乙丙还小，这是因为甲难度S率较低。而一些限定甲难度S胜掉落的船只（如E5的U511）的掉率则恐怖的小，这是因为两方面的统计都没有排除一部分无效样本……

个人认为，做出一个九宫格的掉率统计技术上并不是不可行，既然已经完全统计了一次掉落的难度和战斗结果，那么为何不做出一个准确可参考的数据呢？

**Comment by Gizeta** [comment]
技术上确实可行，只是目前的前端设计并没有打算显示有复杂关系的数据信息，所以就没有做。
我会优先考虑在数据json中加上的。

**Comment by JenningsWu** [comment]
支持，感觉掉落统计的概率按S胜计算（或者增加按S胜计算的数据）更科学一些。
例如本次活动E3 Boss点的瑞穗掉落统计，目前是：
> ## 难度统计：
>  甲难度25 (0.43%)
>  乙难度188 (1.08%)
>  丙难度302 (1.82%)
甲乙难度掉率比丙掉率更低。这是因为高难度更难拿S胜。如果增加S胜下的掉率统计，则用户可以根据自己的实际情况考虑该打哪个难度了。
