### ISSUE TITLE
关于活动人数统计

### ISSUE THREAD

**Issue by JenningsWu** [Gizeta/poi-statistics#3]
活动统计中的人数统计那里有点没看懂。
在"总"那里显示
> 总人数： 1334

但是从后面分条目来看，人数已经超2000人了？比如e4
> 总人数： 2337

**Comment by Gizeta** [comment]
“总”那个页面显示的是当前未通关的总人数
后面的分条目是统计了全部的人数。

稍后我会加些文字区别一下。
